apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dialogmote-frontend-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  tokenx:
    enabled: false
  idporten:
    enabled: false
    sidecar:
      enabled: false
  liveness:
    path: syk/dialogmoter/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/dialogmoter/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://demo.ekstern.dev.nav.no/syk/dialogmoter"
  accessPolicy:
    outbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
      external:
        - host: nav.no
        - host: dekoratoren.nav.no
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp
    - name: DECORATOR_ENV
      value: "prod"
    - name: ISDIALOGMOTE_HOST
      value: http://isdialogmote.teamsykefravr
    - name: SYFOMOTEBEHOV_HOST
      value: https://syfomotebehov.dev-fss-pub.nais.io
    - name: SYKMELDINGER_ARBEIDSGIVER_HOST
      value: https://sykmeldinger-arbeidsgiver.dev.nav.no
    - name: OPPLAERING
      value: "true"
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "test"
    - name: DINE_SYKMELDTE_ROOT
      value: https://www.nav.no/arbeidsgiver/sykmeldte
    - name: DITT_SYKEFRAVAER_ROOT
      value: https://www.nav.no/syk/sykefravaer
    - name: MIN_SIDE_ROOT
      value: https://www.nav.no/minside/
    - name: BASE_PATH
      value: /syk/dialogmoter
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/client/features?tag[]=simple:dialogmote
    - name: DISPLAY_TESTSCENARIO_SELECTOR
      value: "true"
