apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dialogmote-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  tokenx:
    enabled: false
  idporten:
    enabled: false
    sidecar:
      enabled: false
  liveness:
    path: syk/dialogmoter/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/dialogmoter/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://www.nav.no/syk/dialogmoter"
  env:
    - name: DECORATOR_URL
      value: https://nav.no/dekoratoren
    - name: DECORATOR_ENV
      value: "prod"
    - name: LOGINSERVICE_URL
      value: https://loginservice.nav.no/login
    - name: ISDIALOGMOTE_HOST
      value: https://isdialogmote.nav.no
    - name: SYFOMOTEBEHOV_HOST
      value: https://syfomotebehov.prod-fss-pub.nais.io
    - name: SYKMELDINGER_ARBEIDSGIVER_HOST
      value: https://sykmeldinger-arbeidsgiver.nav.no
    - name: OPPLAERING
      value: "false"
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "prod"
    - name: DINE_SYKMELDTE_ROOT
      value: https://www.nav.no/sykefravaerarbeidsgiver
    - name: DITT_SYKEFRAVAER_ROOT
      value: https://www.nav.no/syk/sykefravaer
    - name: BASE_PATH
      value: /syk/dialogmoter
  accessPolicy:
    outbound:
      rules:
        - application: isdialogmote
      external:
        - host: syfomotebehov.prod-fss-pub.nais.io
