apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dialogmote-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: syk/dialogmoter/api/isAlive
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: syk/dialogmoter/api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://www.ekstern.dev.nav.no/syk/dialogmoter"
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp
    - name: DECORATOR_URL
      value: https://dekoratoren.dev.nav.no
    - name: DECORATOR_ENV
      value: "dev"
    - name: ISDIALOGMOTE_HOST
      value: http://isdialogmote.teamsykefravr
    - name: SYFOMOTEBEHOV_HOST
      value: http://syfomotebehov
    - name: DINESYKMELDTE_BACKEND_HOST
      value: http://dinesykmeldte-backend
    - name: OPPLAERING
      value: "false"
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "test"
    - name: DINE_SYKMELDTE_ROOT
      value: https://www-gcp.dev.nav.no/arbeidsgiver/sykmeldte
    - name: DITT_SYKEFRAVAER_ROOT
      value: https://www.ekstern.dev.nav.no/syk/sykefravaer
    - name: MIN_SIDE_ROOT
      value: https://www.dev.nav.no/minside/
    - name: BASE_PATH
      value: /syk/dialogmoter
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/client/features?tag[]=simple:dialogmote
    - name : SYFOMOTEBEHOV_CLIENT_ID
      value: "dev-gcp:team-esyfo:syfomotebehov"
    - name : DINESYKMELDTE_BACKEND_CLIEND_ID
      value: "dev-gcp:team-esyfo:dinesykmeldte-backend"
    - name : ISDIALOGMOTE_CLIENT_ID
      value: "dev-gcp:teamsykefravr:isdialogmote"
    - name: DISPLAY_TESTSCENARIO_SELECTOR
      value: "false"
  accessPolicy:
    outbound:
      rules:
        - application: isdialogmote
          namespace: teamsykefravr
        - application: sykmeldinger-arbeidsgiver
          namespace: teamsykmelding
        - application: nav-dekoratoren
          namespace: personbruker
        - application: syfomotebehov
        - application: dinesykmeldte-backend
      external:
        - host: dekoratoren.dev.nav.no
