name: Build & Deploy
on:
  push:
  workflow_dispatch:

jobs:
  next-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/next-app.yaml@remove-deprecated-4
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      app: dialogmote-frontend
      base-path: /syk/dialogmoter
