name: Demo delete
on:
  delete:
  workflow_dispatch:

jobs:
  branch-delete:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/next-app-demo-delete.yaml@main
    secrets: inherit
    with:
      app: dialogmote-frontend
      base-path: /syk/dialogmoter
